### PR TITLE
Get prefixed cmdlets

### LINKED ISSUE #112: Get-ModuleCommand should (optionally?) look at Value in ExportedCommands
**Is your feature request related to a problem? Please describe.**
I have a module that uses a DefaultCommandPrefix to disambiguate from built-in cmdlet names. Get-ModuleCommand operates on the key which is the command name before applying the prefix. This causes it to query info on the built-in command versus my command.

Example:

`DefaultCommandPrefix = 'my'`
`New-Service` vs `New-myService`

I want info on `New-myService`

**Describe the solution you'd like**
If `Key -ne Value`, use `Value` in [Get-ModuleCommand.ps1#L53](https://github.com/jdhitsolutions/PSScriptTools/blob/master/functions/Get-ModuleCommand.ps1#L53)

**Describe alternatives you've considered**
I don't see anywhere that `DefaultCommandPrefix` is exposed to the runtime so you can programmatically check.

I believe you could also always just use Value instead of Key.

**Additional context**

```dos
Get-Module myModule| Select-Object -ExpandProperty ExportedCommands


Key                      Value
---                      -----
Get-Client               Get-myClient
Get-Config               Get-myConfig
Get-CurrentContext       Get-myCurrentContext
Get-Namespace            Get-myNamespace
Get-Service              Get-myService
New-Namespace            New-myNamespace
New-Service              New-myService
New-ServicePort          New-myServicePort
New-ServiceSpec          New-myServiceSpec
Remove-Namespace         Remove-myNamespace
Remove-Service           Remove-myService
Set-Namespace            Set-myNamespace
Set-Service              Set-myService
```

```dos
Get-ModuleCommand

   ModuleName: myModule

Name                     Alias      Synopsis
----                     -----      --------
Get-Service              gsv        Gets the services on the computer.
New-Service                         Creates a new Windows service.
Remove-Service                      Removes a Windows service.
Set-Service                         Starts, stops, and suspends a service, and changes its properties.
```

### PR DESCRIPTION
**Pull request by cdhunt**
It looks like this is only an issue for binary cmdlets and ToString() on the CmdletInfo object returns the prefixed command name.

Fixes #112

### CODE REVIEW

**Comment by jdhitsolutions** [comment]
This doesn't work on exported functions in PowerShell 7.  The only way `Get-ModuleCommand` works as expected in PowerShell 7 is if you first import the module so that the prefix is applied.

**Comment by cdhunt** [comment]
The prefix can be pulled from `$mod.prefix` and I guess some string formatting down where ` $PSVersionTable.PSVersion -ge 7.0`?

**Comment by jdhitsolutions** [comment]
Since Microsoft agrees there is a PowerShell 7 bug, I'm going to hold off on doing anything. This is only an issue when using `-ListAvailable` in PowerShell 7. This isn't a problem if the module has been imported with the prefix first.

**Comment by jdhitsolutions** [comment]
Ignoring the issue for now, and this PR is so far out of alignment with the current state of the project with too many merge conflicts to manage.

**Pull request closed without merging**
